### ISSUE TITLE
GBFS for Dordrecht?

### ISSUE THREAD

**Issue by oobrien** [DonkeyRepublic/donkey_gbfs#1]
Hi, is there a GBFS feed for the new Dordrecht fleet?

**Comment by trojkac** [comment]
Hi @oobrien,

it is available now: https://github.com/DonkeyRepublic/donkey_gbfs/commit/c9a034e2327d9be9e0e39862d6a050343bbfe8db.

**Comment by oobrien** [comment]
@trojkac Thank you.
