### ISSUE TITLE
All feeds with free_bike_status are invalid

### ISSUE THREAD

**Issue by futuretap** [DonkeyRepublic/donkey_gbfs#4]
The [Aarhus free_bike_status Feed](https://stables.donkey.bike/api/public/gbfs/2/donkey_aarhus/en/free_bike_status.json) is invalid. It contains a `data` in a `data` element. Can you please fix it?

Also affected:

- Bandholm
- Klampenborg
- Moreton In Marsh
- Plymouth
- Porvoo
- Valenciennes
- Antwerp
- Kiel
- Gorinchem

**Comment by trojkac** [comment]
Hi @futuretap, thanks for reporting. Our team will work on a fix. Updates to follow soon.

**Comment by trojkac** [comment]
Hi @futuretap , the issue was resolved.

**Comment by futuretap** [comment]
Awesome, thank you very much, @trojkac!
