### ISSUE TITLE
free_bike_status is not spec conform

### ISSUE THREAD

**Issue by hbruch** [DonkeyRepublic/donkey_gbfs#6]
For a couple of feeds (e.g. https://stables.donkey.bike/api/public/gbfs/2/donkey_ge/fr/free_bike_status.json), the currently generated `free_bike_status` is not spec conform:

* lat/lon should be floats
* last_reported should (for GBFS version < 3.0) be in seconds since epoch
* current_fuel_percent should be float not string
* hub_id should be station_id
* vehicle_type_id  is missing
<img width="698" alt="grafik" src="https://github.com/DonkeyRepublic/donkey_gbfs/assets/2187389/e732dc29-4455-4e7f-af25-72604683e4db">

**Comment by trojkac** [comment]
Thanks for feedback, we have addressed your points and the fix is being deployed.

**Comment by hbruch** [comment]
Looks great, thank you! Closing this issue as solved.
