### ISSUE TITLE
feed_contact_email does not exist

### ISSUE THREAD

**Issue by hbruch** [DonkeyRepublic/donkey_gbfs#7]
The currently in feeds (e.g.  https://stables.donkey.bike/api/public/gbfs/2/donkey_ge/fr/system_information.json) provided feed_contact_email `gbfs at donkeyrepublic dot com` does not exist (at least that is the response I received when trying to reach out)

**Comment by trojkac** [comment]
Hi, we have changed it to support@donkeyrepublic.com. Thanks for reporting!
